# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faces',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='myphoto/'),
        ),
    ]
